### ISSUE TITLE
from where do you get the deviceId? is it IMEI or ANDROID_ID?

### ISSUE THREAD

**Issue by basmasrour** [delight-im/Android-BaseLib#1]

**Comment by ocram** [comment]
Good question!

[`Identity.getInstallationId`](https://github.com/delight-im/Android-Commons/blob/f220021846f66917d56d465c7150bce9b585c08d/Source/library/src/main/java/im/delight/android/commons/Identity.java#L48) should be private and local to your app’s installation on a single device, lasting until it has been uninstalled.

[`Identity.getDeviceId`](https://github.com/delight-im/Android-Commons/blob/f220021846f66917d56d465c7150bce9b585c08d/Source/library/src/main/java/im/delight/android/commons/Identity.java#L94) uses either `android.provider.Settings.Secure.ANDROID_ID`, `android.os.Build.SERIAL`, or the installation ID described above.
